version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build: .
    environment:
      - APP_VERSION=V0.0
      - DB_CONNECTION=host=postgres_db port=5432 user=user dbname=mydatabase password=password sslmode=disable
      - JWT_SECRET=SECRET
      - REFRESH_SECRET=RSECRET


    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - "8080:8080"

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
