
services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork
    environment:
      APP_VERSION: V0.0
      DB_CONNECTION: "host=db port=5432 user=user dbname=mydatabase password=password sslmode=disable"
      JWT_SECRET: SECRET
      REFRESH_SECRET: RSECRET
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge