name: Run tests and upload coverage

on:
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'

      - name: Install dependencies
        run: go mod download

      - name: Install mod
        run: go mod tidy

      - name: Run tests
        run: go test -coverprofile=coverage.txt

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
