name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go (или другой язык, если требуется)
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.4'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
