name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: SSH into server and update
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            export APP_VERSION=V0.0
            export DB_CONNECTION="host=172.18.0.2  port=5432 user=user dbname=mydatabase password=password sslmode=disable"
            export JWT_SECRET=SECRET
            export REFRESH_SECRET=RSECRET
            
            cd /home/igor/gobackend/PrograMentor && git pull origin main
            fuser -k 8080/tcp
            /snap/bin/docker compose down
            /snap/bin/docker compose up -d --build
            /usr/local/go/bin/go run .
            exit 0
